apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  labels:
    app: sentiment-analysis
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: sentiment-analysis
