apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis-deployment
  labels:
    app: sentiment-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
        - name: sentiment-analysis
          image: sentiment-analysis-api:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: FLASK_ENV
              value: production
            - name: PYTHONUNBUFFERED
              value: "1"
